version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
      day: "thu"
      time: "14:10"
    commit-message:
      prefix: "deps"
