apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: geth-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: geth
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: geth
      minAllowed:
        cpu: 1500m
        memory: 4Gi 
      maxAllowed:
        cpu: 4000m
        memory: 16Gi 
