apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: lighthouse-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: StatefulSet
    name: lighthouse
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: lighthouse
      minAllowed:
        cpu: 1500m
        memory: 16Gi
      maxAllowed:
        cpu: 1500m
        memory: 16Gi