apiVersion: apps/v1
kind: Deployment
metadata:
  name: geth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geth
  template:
    metadata:
      labels:
        app: geth
    spec:
      containers:
        - name: geth
          image: ethereum/client-go:stable
          volumeMounts:
            - name: geth-data
              mountPath: /.holesky
            - name: jwt-secret
              mountPath: /.holesky/jwtsecret
              subPath: jwt-secret
          env:
            - name: GETH_PORT
              value: "8545"
          command:
            - geth
          args:
            - --holesky
            - --http
            - --http.addr=0.0.0.0
            - --http.port=8547
            - --http.api=eth,net,web3,txpool
            - --http.corsdomain=*
            - --http.vhosts=*
            - --metrics
            - --metrics.addr=0.0.0.0
            - --metrics.port=6060
            - --ws
            - --ws.addr=0.0.0.0
            - --ws.port=8546
            - --ws.api=eth,net,web3,txpool
            - --ws.origins=*
            - --graphql
            - --graphql.corsdomain=*
            - --graphql.vhosts=*
            - --syncmode=snap
            - --datadir=/.holesky
            - --verbosity=3
            - --nousb
            - --authrpc.addr=0.0.0.0
            - --authrpc.port=8551
            - --authrpc.vhosts=*
            - --authrpc.jwtsecret=/.holesky/jwtsecret
      volumes:
        - name: geth-data
          hostPath:
            path: /Users/sia/geth-data2
        - name: jwt-secret
          secret:
            secretName: geth-jwt-secret

---
apiVersion: v1
kind: Service
metadata:
  name: geth
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8547
      targetPort: 8547
    - name: ws
      port: 8546
      targetPort: 8546
    - name: authrpc
      port: 8551
      targetPort: 8551
    - name: p2p
      port: 30303
      targetPort: 30303
    - name: metrics
      port: 6060
      targetPort: 6060
  selector:
    app: geth