apiVersion: apps/v1
kind: Deployment
metadata:
  name: beacon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beacon
  template:
    metadata:
      labels:
        app: beacon
    spec:
      containers:
        - name: beacon
          image: sigp/lighthouse:latest-modern
          ports:
            - name: http
              containerPort: 5052
            - name: metrics
              containerPort: 5053
            - name: p2p
              containerPort: 9000
          envFrom:
            - configMapRef:
                name: lighthouse-config
          env:
            - name: JWT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: geth-jwt-secret
                  key: jwt-secret
          command:
            - lighthouse
            - --network
            - mainnet
            - beacon
            - --staking
            - --validator-monitor-auto
            - --http
            - --http-address=0.0.0.0
            - --http-port=5052
            - --metrics
            - --metrics-address=0.0.0.0
            - --metrics-port=5053
            - --suggested-fee-recipient=$(FEE_RECIPIENT)
            - --execution-endpoint=$(EXECUTION_ENDPOINT)
            - --execution-jwt=/root/.lighthouse/jwtsecret
            - --prune-payloads=false
            - --checkpoint-sync-url=https://beaconstate.ethstaker.cc
          volumeMounts:
            - name: lighthouse-data
              mountPath: /root/.lighthouse
            - name: validator-keys
              mountPath: /root/validator_keys
            - name: jwt-secret
              mountPath: /root/.lighthouse/jwtsecret
              subPath: jwt-secret
              readOnly: true
      volumes:
        - name: lighthouse-data
          hostPath:
            path: /Users/sia/lb-data  # 호스트에서 이 경로가 존재하는지 확인
        - name: validator-keys
          hostPath:
            path: /keys/validator_keys  # 호스트에서 이 경로가 존재하는지 확인
        - name: jwt-secret
          secret:
            secretName: geth-jwt-secret
---
apiVersion: v1
kind: Service
metadata:
  name: beacon
spec:
  ports:
    - name: http
      port: 5052
      targetPort: 5052
    - name: metrics
      port: 5053
      targetPort: 5053
    - name: p2p
      port: 9000
      targetPort: 9000
  selector:
    app: beacon
