apiVersion: v1
kind: Service
metadata:
  name: lighthouse-svc
spec:
  selector:
    app: validator
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: p2p-tcp
    - port: 5052
      targetPort: 5052
      protocol: TCP
      name: http-tcp
    - port: 5054
      targetPort: 5054
      protocol: TCP
      name: metrics