apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: beacon
spec:
  serviceName: "beacon"
  replicas: 1
  selector:
    matchLabels:
      app: beacon
  template:
    metadata:
      labels:
        app: beacon
    spec:
      containers:
        - name: beacon
          image: sigp/lighthouse:latest-modern
          envFrom:
            - configMapRef:
                name: lighthouse-config
          env:
            - name: JWT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: geth-jwt-secret
                  key: jwt-secret
          command:
            - lighthouse
          args:
            - --network
            - holesky
            - beacon
            - --datadir
            - /root/.lighthouse
            - --staking
            - --validator-monitor-auto
            - --http
            - --http-address=0.0.0.0
            - --http-port=5052
            - --metrics
            - --metrics-address=0.0.0.0
            - --metrics-port=5053
            - --suggested-fee-recipient=$(FEE_RECIPIENT)
            - --execution-endpoint=$(EXECUTION_ENDPOINT)
            - --execution-jwt=/.holesky/jwtsecret
            - --prune-payloads=false
            - --checkpoint-sync-url=https://holesky.beaconstate.ethstaker.cc/
            - --purge-db
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
            limits:
              cpu: "4"
              memory: "8Gi"
          volumeMounts:
            - name: lighthouse-data
              mountPath: /root/.lighthouse/beacon
            - name: validator-keys
              mountPath: /root/validator_keys
            - name: jwt-secret
              mountPath: /.holesky/jwtsecret
              subPath: jwt-secret
              readOnly: true
      volumeClaimTemplates:
        - metadata:
            name: lighthouse-data
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 10Gi
            storageClassName: standard
        - metadata:
            name: validator-keys
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 256Gi
            storageClassName: standard
---
apiVersion: v1
kind: Service
metadata:
  name: beacon
spec:
  ports:
    - name: http
      port: 5052
      targetPort: 5052
    - name: metrics
      port: 5053
      targetPort: 5053
    - name: p2p
      port: 9000
      targetPort: 9000
  selector:
    app: beacon
