apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: lv-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: validator
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: validator
      minAllowed:
        cpu: 2
        memory: 3Gi
      maxAllowed:
        cpu: 4
        memory: 10Gi
