apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: lb-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: beacon
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: beacon
      minAllowed:
        cpu: 2
        memory: 3Gi
      maxAllowed:
        cpu: 4
        memory: 8Gi
