apiVersion: v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: geth-pv
spec:
  capacity:
    storage: 1400Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: /home/staker/data/geth # local path

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lb-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: /home/staker/data/lb   # local path
  persistentVolumeReclaimPolicy: Retain
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: lv-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: /home/staker/data/lv   # local path
  persistentVolumeReclaimPolicy: Retain

