apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lv-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi  
  storageClassName: standard 

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: validator-keys-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  
  storageClassName: standard  
