apiVersion: apps/v1
kind: Deployment
metadata:
  name: geth-deployment
  labels:
    app: validator
spec:
  selector:
    matchLabels:
      app: validator
      comp: geth-node-pod
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: validator
        comp: geth-node-pod
    spec:
      containers:
        - name: geth-node-pod
          image: ethereum/client-go:stable
          args: 
            --http
            --http.addr=0.0.0.0
            --http.port=8545
            --http.vhosts=*
            --http.corsdomain=*
            --ws
            --ws.addr=0.0.0.0
            --ws.port=8545
            --ws.origins=*
            --authrpc.jwtsecret=/data/jwt.hex
            --authrpc.addr=0.0.0.0
            --authrpc.port=8551
            --authrpc.vhosts=*
            --metrics
            --metrics.addr=0.0.0.0
            --metrics.port=6060
          resources:
            limits:
              cpu: 4000m
              memory: 16Gi
            requests:
              cpu: 1500m
              memory: 4Gi
          ports:
            - containerPort: 8545
              name: rpc-port
            - containerPort: 8546
              name: ws-port
            - containerPort: 8551
              name: exec-port-tcp
            - containerPort: 30303
              name: p2p-port-tcp
            - containerPort: 30304
              name: p2p-port-udp
              protocol: UDP
          startupProbe:
            tcpSocket:
              port: 8551
            failureThreshold: 30 # 5 minutes (30 * 10 = 300s) to finish startup
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8551
            initialDelaySeconds: 15
            timeoutSeconds: 5
          volumeMounts:
            - name: geth-ssd
              mountPath: /var/geth/           
            - name: jwt-secret
              mountPath: /etc/jwt/
              readOnly: true
      volumes:
        - name: geth-ssd
          persistentVolumeClaim:
            claimName: geth-pvc
        - name: jwt-secret
          secret:
            secretName: jwt-secret

